# File: .github/workflows/repo-sync.yml
name: repo-sync

on:
  schedule: 
  - cron: "0 3 27 * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: ${{ secrets.SOURCE_REPO }} # source repo e.g. "https://github.com/ie13/ios_rule_script.git"
        source_branch: ${{ secrets.SOURCE_BRANCH }} # e.g. master
        destination_branch: ${{ secrets.SOURCE_BRANCH }} # e.g. master
        github_token: ${{ secrets.PAT }}
